# Generated by Django 3.2.10 on 2022-04-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodcut',
            new_name='product',
        ),
    ]
