# Generated by Django 3.2.10 on 2022-04-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
